baseURL = 'https://barbaradenney.github.io/'
languageCode = 'en-us'
title = 'Barbara Denney - Portfolio'
theme = 'PaperMod'

[params]
  env = "production"
  description = "Barbara Denney's Portfolio Website"
  author = "Barbara Denney"
  
  # Theme settings
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false

  # Home page settings
  homeInfoParams = { Title = "Hi there! 👋", Content = "Welcome to my portfolio website. I'm Barbara Denney." }

  # Social icons
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://linkedin.com/in/"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
    
  [[menu.main]]
    identifier = "projects"
    name = "Projects" 
    url = "/projects/"
    weight = 20
    
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 30
