baseURL = 'https://barbaradenney.github.io/'
languageCode = 'en-us'
title = 'Barbara Denney'
theme = 'PaperMod'

# Google Analytics
googleAnalytics = 'G-FH6DS1H052'

[privacy]
  [privacy.googleAnalytics]
    respectDoNotTrack = true
    anonymizeIP = true

[params]
  env = "production"
  description = "Barbara Denney"
 
  
  # Theme settings
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = true
  showtoc = false
  tocopen = false

  # Home page settings
  homeInfoParams = { Title = "Hi there! 👋", Content = "I'm Barbara Denney, a Designer that specializes in creating accessible scalable Design Systems for government agencies. I work in Figma and code." }

  # Social icons
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/babsdenney"
    title = "GitHub"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/barbara-denney/"
    title = "LinkedIn"

  [[params.socialIcons]]
    name = "cv"
    url = "/Barbara-Denney-Resume.pdf"
    title = "Resume"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
    
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 20

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 30
